services:
  postgres:
    image: postgres:17.11-alpine
    container_name: ledgerguard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ledgerguard}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set in .env}
      LEDGERGUARD_DB_USER: ${LEDGERGUARD_DB_USER:-ledgerguard_app}
      LEDGERGUARD_DB_PASSWORD: ${LEDGERGUARD_DB_PASSWORD:?LEDGERGUARD_DB_PASSWORD must be set in .env}
      PSP_DB_USER: ${PSP_DB_USER:-psp_simulator_app}
      PSP_DB_PASSWORD: ${PSP_DB_PASSWORD:?PSP_DB_PASSWORD must be set in .env}
      NOTIFICATION_DB_USER: ${NOTIFICATION_DB_USER:-notification_worker_app}
      NOTIFICATION_DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD:?NOTIFICATION_DB_PASSWORD must be set in .env}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ledgerguard-postgres-data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-ledgerguard}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ledgerguard-network

  kafka:
    image: apache/kafka:4.3.1
    container_name: ledgerguard-kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:${KAFKA_PORT:-29092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: 4L622nShTUiBenVKBpahFQ
    ports:
      - "${KAFKA_PORT:-29092}:29092"
    volumes:
      - ledgerguard-kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - ledgerguard-network

volumes:
  ledgerguard-postgres-data:
    name: ledgerguard-postgres-data
  ledgerguard-kafka-data:
    name: ledgerguard-kafka-data

networks:
  ledgerguard-network:
    name: ledgerguard-network
