package com.ledgerguard.audit.domain;

public enum AuditAction {
    RECONCILIATION_CASE_CLAIMED,
    RECONCILIATION_SNAPSHOT_REPAIRED,
    RECONCILIATION_ALREADY_CONSISTENT,
    RECONCILIATION_CASE_MANUALLY_RESOLVED
}